from . import res_region  # noqa: F401
from . import res_country  # noqa: F401
from . import ir_ui_view  # noqa: F401
from . import ir_ui_menu  # noqa: F401
from . import res_group  # noqa: F401
from . import res_user  # noqa: F401
from . import ir_model_access  # noqa: F401
from . import ir_rule  # noqa: F401
from . import actions  # noqa: F401
from . import res_company  # noqa: F401
from . import res_currency  # noqa: F401
from . import res_currency_rate  # noqa: F401
from . import ir_attachment  # noqa: F401
