"""Oracle dialect helpers."""
from __future__ import annotations

from typing import TYPE_CHECKING

from ..capabilities import DialectCapabilities, SchemaResetStrategy

if TYPE_CHECKING:
    from ..adapter import ConnectionAdapter

NAME = "oracle"

CAPABILITIES = DialectCapabilities(
    name=NAME,
    supports_returning=True,
    supports_ilike=False,
    supports_add_column_if_not_exists=False,
    supports_drop_schema=False,
    schema_reset=SchemaResetStrategy.DROP_ALL_TABLES,
    placeholder="%s",
)

PORTABLE_TYPE_MAP = {
    "double precision": "FLOAT",
    "timestamptz": "TIMESTAMP WITH TIME ZONE",
    "timestamp": "TIMESTAMP",
    "boolean": "NUMBER(1)",
    "text": "CLOB",
    "integer": "INTEGER",
    "SERIAL": "INTEGER",
}


def normalize_dsn(dsn: str) -> str | None:
    if dsn.startswith("oracle://") and "+oracledb" not in dsn.split(":", 1)[0]:
        return "oracle+oracledb://" + dsn[len("oracle://") :]
    return None


def configure_engine(engine) -> None:
    return None


def serial_primary_key() -> str:
    return '"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'


def fetch_lastrowid(conn: ConnectionAdapter, table: str) -> int:
    row = conn.execute(f'SELECT MAX("id") FROM "{table}"').fetchone()
    return int(row[0]) if row and row[0] is not None else 0


def timestamp_sql_type() -> str:
    return "TIMESTAMP WITH TIME ZONE"


def now_sql() -> str:
    return "SYSTIMESTAMP"


def string_sql_type(*, primary_key: bool = False) -> str:
    return "VARCHAR2(255)" if primary_key else "CLOB"


def supports_create_table_if_not_exists() -> bool:
    return False


def append_search_pagination(
    sql: str,
    *,
    base_table_sql: str,
    limit: int | None,
    offset: int,
    order: str | None,
) -> str:
    if " ORDER BY " not in sql.upper():
        if order:
            sql += f" ORDER BY {order}"
        else:
            sql += f' ORDER BY {base_table_sql}."id"'
    sql += f" OFFSET {int(offset)} ROWS"
    if limit is not None:
        sql += f" FETCH NEXT {int(limit)} ROWS ONLY"
    return sql


def bind_params(params: tuple) -> tuple:
    return params


def is_duplicate_column_error(msg: str) -> bool:
    return "already exists" in msg or "name is already used" in msg


def is_missing_table_error(msg: str) -> bool:
    return "ora-00942" in msg or "does not exist" in msg


def before_reset_all_tables(conn: ConnectionAdapter) -> None:
    return None


def after_reset_all_tables(conn: ConnectionAdapter) -> None:
    return None


def reset_all_tables(conn: ConnectionAdapter) -> None:
    """Authoritatively wipe every object the connecting user owns.

    The generic reset enumerates tables through the SQLAlchemy inspector, but
    on Oracle that is unreliable: ``get_table_names()`` hides recyclebin
    entries, and a plain ``DROP TABLE`` (Oracle's default) only *renames* the
    table into the recyclebin instead of removing it. Leftover objects then
    resurface as ``ORA-00955: name is already used`` on the next CREATE.

    Query ``user_tables`` directly (the authoritative live-table view), drop
    each with ``CASCADE CONSTRAINTS PURGE`` so foreign keys and the recyclebin
    can't get in the way, then ``PURGE RECYCLEBIN`` to clear anything an older
    non-purging drop left behind.
    """
    from ..sa_ddl import execute_sql

    rows = execute_sql(conn, "SELECT table_name FROM user_tables").fetchall()
    for row in rows:
        table_name = row[0]
        execute_sql(conn, f'DROP TABLE "{table_name}" CASCADE CONSTRAINTS PURGE')
    execute_sql(conn, "PURGE RECYCLEBIN")
