"""Migration 0.16.0 → 0.17.0 — introduce ``ir.attachment``.

Autogenerated by ``pyvelm db autogen base`` and lightly massaged:
* DDL split across lines for readability.
* Added a composite index on ``(res_model, res_id)`` since every
  attachment-widget read scans by host record; the loader doesn't
  emit indexes for non-FK columns.
* Grants Admin full CRUD on ``ir.attachment`` (fresh installs get
  the same grant via the install hook).

Fresh installs hit this code path through ``_setup_table`` (idempotent
CREATE TABLE IF NOT EXISTS); existing 0.16 installs upgrade through
this script.
"""


def migrate(env):
    env.conn.execute(
        'CREATE TABLE IF NOT EXISTS "ir_attachment" ('
        '"id" SERIAL PRIMARY KEY, '
        '"name" text NOT NULL, '
        '"datas_fname" text, '
        '"mimetype" text, '
        '"file_size" integer, '
        '"res_model" text, '
        '"res_id" integer, '
        '"type" text, '
        '"url" text, '
        '"storage_key" text, '
        '"datas" text'
        ")"
    )
    env.conn.execute(
        'CREATE INDEX IF NOT EXISTS "ir_attachment_res_idx" '
        'ON "ir_attachment" ("res_model", "res_id")'
    )
    # Mirror the install-hook grant for already-installed databases.
    # Idempotent: skip the insert if the row already exists. We look
    # the Admin group up by name; if it's missing (rare — only on
    # databases pre-dating the Admin seed), skip the grant entirely.
    if "ir.model.access" in env.registry and "res.groups" in env.registry:
        Access = env["ir.model.access"]
        Group = env["res.groups"]
        admin = Group.search([("name", "=", "Admin")], limit=1)
        if admin and not Access.search(
            [("model", "=", "ir.attachment"), ("group_id", "=", admin.id)],
            limit=1,
        ):
            Access.create({
                "name": "Admin/ir.attachment",
                "model": "ir.attachment",
                "group_id": admin,
                "perm_read": True,
                "perm_write": True,
                "perm_create": True,
                "perm_unlink": True,
            })
